# Generated by Django 5.1.5 on 2025-01-21 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 4, 18, 52, 298597, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='finalFecha',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 21, 4, 18, 52, 313596, tzinfo=datetime.timezone.utc)),
        ),
    ]
