# Generated by Django 5.1.5 on 2025-01-21 04:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_asistencia_fecha_alter_asistencia_finalfecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='finalFecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
