# Generated by Django 5.1.5 on 2025-01-21 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_asistencia_fecha_alter_asistencia_finalfecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciacompleta',
            name='salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salida_completa', to='personal.asistencia'),
        ),
    ]
