# Generated by Django 5.1.5 on 2025-01-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_asistenciacompleta_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='ultimaAsistenciaProcesada',
            field=models.IntegerField(default=0),
        ),
    ]
